[window]
opacity = 0.6

[font]
size = 10.0

[font.bold]
family = "Hack"
style = "Bold"

[font.bold_italic]
family = "Hack"
style = "Bold"

[font.italic]
family = "Hack"
style = "Bold"

[font.normal]
family = "Hack"
style = "Bold"
